# Generated by Django 4.2.4 on 2023-08-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel_Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('price', models.PositiveIntegerField()),
                ('reserved', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomApplication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.DateField()),
                ('total_price', models.PositiveIntegerField(null=True)),
                ('approve_status', models.CharField(choices=[(False, 'Отклонено'), (True, 'Одобрено'), ('Not checked', 'Не проверено')], default='Not checked', max_length=50)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hotel_Client.client')),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hotel_Admin.rooms')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_Admin.service')),
            ],
        ),
    ]
