# Generated by Django 4.2.4 on 2023-08-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomapplication',
            name='start_time',
            field=models.DateField(),
        ),
    ]
