# Generated by Django 4.2.4 on 2023-08-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Admin', '0002_alter_roomapplication_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomapplication',
            name='services',
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='services',
            field=models.ManyToManyField(to='Hotel_Admin.service'),
        ),
    ]
