# Generated by Django 4.2.5 on 2023-09-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Client', '0001_initial'),
        ('Hotel_Admin', '0003_remove_roomapplication_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomapplication',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_Client.client'),
        ),
    ]
