# Generated by Django 4.2.5 on 2023-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Admin', '0004_alter_roomapplication_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('cheap', 'дешевый'), ('middle', 'средний'), ('expensive', 'дорогой')], max_length=50, null=True),
        ),
    ]
